export const fases = [
  {
    id: 1,
    som: process.env.PUBLIC_URL + '/sons/gato.mp3',
    opcoes: ['Cachorro','Gato','Vaca','Passarinho'],
    respostacerta: 'Gato',
  },
  {
    id: 2,
    som: process.env.PUBLIC_URL + '/sons/cavalo.mp3',
    opcoes: ['Cavalo', 'Leão', 'Galo', 'Elefante'],
    respostacerta: 'Cavalo',
  },
  {
    id: 3,
    som: process.env.PUBLIC_URL + '/sons/macaco.mp3',
    opcoes: ['Porco','Coelho' , 'Macaco', 'Tigre'],
    respostacerta: 'Macaco',
  },
  {
    id: 4,
    som: process.env.PUBLIC_URL + '/sons/cobra.mp3',
    opcoes: ['Coruja', 'Cobra', 'Lobo', 'Pato'],
    respostacerta: 'Cobra',
  },
  {
    id: 5,
    som: process.env.PUBLIC_URL + '/sons/raposa.mp3',
    opcoes: ['Urso', 'Cavalo-marinho', 'Golfinho', 'Raposa'],
    respostacerta: 'Raposa',
  },
  {
    id: 6,
    som: process.env.PUBLIC_URL + '/sons/zebra.mp3',
    opcoes: ['Zebra', 'Jacaré', 'Cervo', 'Arara'],
    respostacerta: 'Zebra',
  },
  {
    id: 7,
    som: process.env.PUBLIC_URL + '/sons/leao-marinho.mp3',
    opcoes: ['Leão-marinho', 'Tatu', 'Morcego', 'Foca'],
    respostacerta: 'Leão-marinho',
  },
  {
    id: 8,
    som: process.env.PUBLIC_URL + '/sons/anta.mp3',
    opcoes: [ 'Camelo', 'Anta', 'Búfalo', 'Jacaré'],
    respostacerta: 'Anta',
  },
  {
    id: 9,
    som: process.env.PUBLIC_URL + '/sons/suricato.mp3',
    opcoes: ['Rena', 'Suricato', 'Esquilo', 'Corvo'],
    respostacerta: 'Suricato',
  },
  {
    id: 10,
    som: process.env.PUBLIC_URL + '/sons/galo-da-serra.mp3',
    opcoes: ['Bicho-preguiça', 'Galo-da-serra', 'Tamanduá', 'Andorinha'],
    respostacerta: 'Galo-da-serra',
  },
  {
    id: 11,
    som: process.env.PUBLIC_URL + '/sons/pavao.mp3',
    opcoes: ['Lobo-guará', 'Guaxinim', 'Pavão', 'Ganso'],
    respostacerta: 'Pavão',
  },
  {
    id: 12,
    som: process.env.PUBLIC_URL + '/sons/morcego.mp3',
    opcoes: ['Morcego', 'Falcão', 'Papagaio', 'Galo'],
    respostacerta: 'Morcego',
  },
  {
    id: 13,
    som: process.env.PUBLIC_URL + '/sons/pantera.mp3',
    opcoes: ['Crocodilo', 'Canguru', 'Pantera', 'Coiote'],
    respostacerta: 'Pantera',
  },
  {
    id: 14,
    som: process.env.PUBLIC_URL + '/sons/aguia.mp3',
    opcoes: ['Tartaruga', 'Camaleão', 'Guará', 'Águia'],
    respostacerta: 'Águia',
  },
  {
    id: 15,
    som: process.env.PUBLIC_URL + '/sons/cervo.mp3',
    opcoes: ['Cervo', 'Onça-pintada', 'Rato', 'Foca'],
    respostacerta: 'Cervo',
  },
  {
    id: 16,
    som: process.env.PUBLIC_URL + '/sons/coruja.mp3',
    opcoes: ['Ganso', 'Coruja', 'Pinguim', 'Antílope'],
    respostacerta: 'Coruja',
  },
  {
    id: 17,
    som: process.env.PUBLIC_URL + '/sons/tamandua-bandeira.mp3',
    opcoes: ['Cavalo', 'Galo-da-serra', 'Tamanduá-bandeira', 'Jacaré'],
    respostacerta: 'Tamanduá-bandeira',
  },
  {
    id: 18,
    som: process.env.PUBLIC_URL + '/sons/urso.mp3',
    opcoes: ['Urso-pardo', 'Tamanduá-bandeira', 'Cervo-do-pantanal', 'Morcego'],
    respostacerta: 'Urso-pardo',
  },
  {
    id: 19,
    som: process.env.PUBLIC_URL + '/sons/corvo.mp3',
    opcoes: ['Corvo', 'Galo', 'Coiote', 'Lobo-guará'],
    respostacerta: 'Corvo',
  },
  {
    id: 20,
    som: process.env.PUBLIC_URL + '/sons/foca.mp3',
    opcoes: [ 'Foca', 'Tigre', 'Búfalo', 'Papagaio'],
    respostacerta: 'Foca',
  },
]